### PR TITLE
save cfg files to dir

### PR DESCRIPTION
**Pull request by cgnitash**
Implements suggestions in #211 
An optional extra option can be passed after the -s flag which specifies which output directory to save the settings files in. (There's no checking to see if the directory actually exists.)

This feature doesn't change any function signatures. 
readCommandLine used to return void. Now it returns the name of the output directory.
initializeParameters used to return a bool. Now it returns a pair<bool,string>, where the bool has the same meaning as before, and the string is the name of the output directory.

### CODE REVIEW

**Comment by JorySchossau** [comment]
This is an awesome PR example of the PR workflow!
My only comments toward the discussion are that 1) it feels weird to be having those functions return something, when that's not really the point of those functions. Is there another way we could pass the data around? 2) My mistake - I forgot to comment on the issue again. Is there a way we could use this to not only specify the output directory, but the prefix to the filenames? I used to use outputDir this way and it was great to separate out my files, but admittedly I haven't done that in a while.

**Comment by cliff-bohm** [comment]
I think I agree with Jory and the behavior should simply be to prepend the string. I.e. if you want to save to a different directory you must specify 'dirname/'

This would add the functionality that one could save the state of their config with a command like: 
```
./mabe -s mondayMorn_
```

This does beg the question, "Should config option **outputDirectory** be called **outputPath** and work the same way?"

**Comment by cgnitash** [comment]
Yeah, I like the idea of settings file prefixes instead of dirs. 
Would "settings_" be considered the default prefix that can be overriden, or would the user specified prefix be prepended?

I like the idea of putting the  settings files configs in the parameter class. There's only one instance of these configs ever. Let me know if that's a problem. If not, I could simply put it in this branch.

It make sense to have output directory behave in the same way, i.e. prefixes instead of dirs. But that would definitely be a different PR.

**Comment by cgnitash** [comment]
prefix behaviour implemented.

settings filles configs are now static data members in Parameters:: 
This means readCommandLine and InitializeParameters don't have to return anything. In fact, readCommandLine no longer needs to take saveFiles as an output parameter.

**Comment by cliff-bohm** [comment]
works for me. I think the static solution is pretty good (can't think of something better...)
The -h option needs to be updated to reflect this change.

**Comment by cgnitash** [comment]
Aah yes, that should happen in this PR.

**Comment by cgnitash** [comment]
So currently, the user specified prefix is prepended to "settings_*", instead of overwriting it, which appears to be the desired behaviour.

**Pull request merged**
