### PR TITLE
Feature neurocorrelates

### PR DESCRIPTION
**Pull request by dkirkpatrick**
Adds the ability to use the neurocorrelates to analyze brains

### CODE REVIEW

**Comment by cgnitash** [comment]
Question about the PR+NeedsTesting label. I thought this meant, test using mtest.py. But this is an entirely new module, so everything will work. Am I missing something?

**Comment by cgnitash** [comment]
I like this module. We may decide that it's better to just keep this stuff in Utilities, but regardless, there's some really nice functionality in here. 

Issues with naming. There are several functions ..ToInt() that return a size_t. Also, there functions like get..Pair() that return a double instead of a pair.

**Comment by cgnitash** [comment]
Most of the functionality in this module is algorithmic computations. This will serve as a good example of using algorithms in code. I'll make a PR for this branch, instead of making changes directly.

**Comment by cgnitash** [comment]
Can this functionality be made header-only?

**Comment by cgnitash** [comment]
There's a lot of redundant computations done, if the api is all free functions. This stuff should be encapsulated, to reduce duplicate computations (and cache stuff)

**Comment by dkirkpatrick** [comment]
With respect to the naming conventions... the get...Pair issue is because there are things I'm referring to as Pairs so it should be viewed as get (XPair) not get (X) Pair 

The get...Int functions could be renamed 

The functionality could be made header-only but I was trying to separate the code out properly

**Comment by JorySchossau** [comment]
@dkirkpatrick Do you have a newer version of this? Just checking.
This all looks good and we should merge this.

**Comment by JorySchossau** [comment]
Also we have no good way of testing this currently. I assume @dkirkpatrick is using these for his research so that is a form of testing? ¯\_(ツ)_/¯

**Pull request merged**
