### PR TITLE
Lexicase edits

### PR DESCRIPTION
**Pull request by cgnitash**
Edits for #221 
Transposes the scores 2D vector. Makes element access more natural, as illustrated in one loop.

This does the change the results, though not qualitatively. Perhaps due to the order in which scores are computed. Not sure if this is a bug though.

### CODE REVIEW

**Comment by cgnitash** [comment]
Made a number of additional code transformations. 
e.g. Implementation details are now the same for any number of parents.

**Comment by cliff-bohm** [comment]
the option should be pool size and not tournament size.
This is not tournament selection and using that term is at least confusing and probably incorrect.

**Comment by cgnitash** [comment]
Ok, then I'll change the implementation accordingly.

**Comment by cgnitash** [comment]
Actually, this branch is supposed to be merged into feature-LexicaseOptimiser if at all, definitely not the other way around. We'll sort this out in lab.

**Pull request closed without merging**
