### PR TITLE
Feature CSV integration

### PR DESCRIPTION
**Pull request by JorySchossau**
Partial merge from #267 (Nitash's CSV work).

Ready for testing - please at least list things that should be in testing.

* `load_value` is now `convertStringToValue`
* `convertCSVListToVector` is now `convertCSVListToValues`
* added `convertVectorOfStringsToValues`
* retained unsafe assignment-conversions as `UNSAFEconvertStringToValue` because they're useful in other code, such as `convertVectorOfStringsToValues`
* removed all '[]' in config files and reading / writing of genome files
* fixed error in CSV.cpp not clearing the last read field before reading the next line
* commented complex x-platform functions in Filesystem

To Do:
- [x] fix only the confusing 80-char line breaks
- [x] replace only the confusing uses of auto
- [x] replace nested std types with appropriate typedefs

### CODE REVIEW

**Comment by JorySchossau** [comment]
More notes for anyone looking at clean up and integration:
* Archivist is getting passed a vector of column names with a single empty string, on a default run. After hacking past this and filling in the right columns (modify `if` statement on line 155 of DefaultArchivist to enter on this condition) then the MABE finishes a default run and data is correctly saved.

**Comment by cliff-bohm** [comment]
creating default cfg files and running with -f settings* results in:

`Error: unrecognised line
  popFileColumns =                           #(string) data to be saved into average file (must be values that can generate an average). If empty, MABE will try in file settings.cfg
See https://github.com/Hintzelab/MABE/wiki/Parameters-Name-Space  for correct usage.
`

when I change the parameter ARCHIVIST_DEFAULT-popFileColumns in settings.cfg from an empty string to "" MABE runs correctly.

**Comment by JorySchossau** [comment]
Parameters.cpp was not allowing blank values. I changed it to allow blank values by capturing everything after the `=` instead of just non-white space. Then I added functionality to strip whitespacing before storing the parameter value, since there obviously will be some now.

**Comment by cliff-bohm** [comment]
There is something wonky with convertCSVListToVector...
convertCSVListToVector gets 'target' a vector which it should fill in.
'target' gets passed to convertVectorOfStringsToVector, but convertVectorOfStringsToVector
creates 'data' and fills that in. the values are never placed in 'target'. do we need 'data'?

What is supposed to be happening here?

**Comment by JorySchossau** [comment]
Sounds like a bug / holdover from when the function returned the data. It
should write to target.

**Comment by JorySchossau** [comment]
I pushed a fix for that issue, @cliff-bohm.
I made some temporary unit tests since we don't have a framework for that, but each of the `convert...` functions passed the tests and did the right thing. Thanks for helping look over this code.

**Pull request merged**
