### PR TITLE
Development

### PR DESCRIPTION
**Pull request by cliff-bohm**

### CODE REVIEW

**Comment by trougnouf** [comment]
The development buildOptions.txt (ie only Test world and no Markov Brains, commit 0042ea73e5052bff1220c071177692ddc2f49ebf  ) don't seem to fit in the master branch.

**Comment by JorySchossau** [comment]
Can you elaborate on what you mean by that? The reasoning for this file being minimalistic is so that it is fast to see if everything is set up correctly to build and run MABE.

**Comment by trougnouf** [comment]
I thought that was just a remnant from the development branch.

The [installation instructions](https://github.com/Hintzelab/MABE/wiki/Installation-and-getting-started-with-MABE) instruct users to download the master branch and run `python PythonTools/MBuild.py`, therefore it seems counter-intuitive for a new user to find that the expected BerryWorld and MarkovBrains are not installed.

**Comment by JorySchossau** [comment]
Yes, we have a lot of work to update the documentation up to master. Sorry
for the confusion!

**Comment by trougnouf** [comment]
Thank you! I changed the package to build everything.

**Pull request merged**
