### PR TITLE
Upgrade islands optimizer

### PR DESCRIPTION
**Pull request by cliff-bohm**
This upgrades IslandsOptimizer to a) add support for Lexicase Optimizer b) handle the case where different optimizers add different data to DataMaps (unassigned columns are filled in with dummy data). This change requires LexicaseOptimizer.

### CODE REVIEW

**Comment by cgnitash** [comment]
This PR seems a good example of whether it makes sense to look at IslandsOptimiser semantics more closely. 
If IslandsOpt knows so much about other Optimisers it makes sense for it to be the top level Optimiser. There could be a "default/fallback" switch that lets Islands run exactly as if a single other Optimiser were being run. 
Also, if many other Optimisers are added to Islands in the same way, then Islands will not work for a few Optimisers which is confusing to users, and goes against the mix-and-match principle.

**Comment by cgnitash** [comment]
Also, this PR should not be merged until #221 is merged, since there's a dependency.

**Comment by cliff-bohm** [comment]
I don't think that we should view this optimizer as the general case. There are other ways that a meta optimizer could be designed. Documentation for this optimizer will need to explain how it uses namespace to describe the individual optimizers.

**Comment by cgnitash** [comment]
This raises some questions. 
1) Would a meta-optimiser handle all use cases of islandsOptimiser?

2) Should we have an optimiser that needs to know about other optimisers?
 a) If one of the other Optimisers changes, does Islands have to be updated?
 b) As I mentioned above, does this go against the mix-and-match philosophy?

**Comment by cliff-bohm** [comment]
This issue goes away if you think of modules in the way that they were conceived. That is, what happens in a module is local to that module. IslandsOptimizer includes other optimizers. Yup, it does. That's fine, it's allowed to do whatever it wants! Will it break if you do not build with one of these optimizers? Yup - and this will be obvious though at compilation. Might it break if one of the optimizers it includes changes? Probably not - as long as those optimizers are playing by the rules and we don't change the rules.

The problem with attempting to make this some general type of object is that we will need to define a lot of additional behavior. This will most likely make some other future module more tricky. The current design allows for modules to get as internally complex as we want without affecting core MABE.

We can talk about whether islands should be in extras and not core, but I will argue for it to be in core since it's a feature that may get a lot of use and, is a good example using namespace.

**Comment by cgnitash** [comment]
Hmm that's some good points. I guess it doesn't matter how complex Islands gets as long no other modules depend on _it_, which they don't.

I haven't looked at the code in detail, but if Islands doesn't make assumptions about the _implementation_ of other Optimisers, and only relies on the AbstractOptimiser interface, then I don't have any objections.

In future discussions about meta-optimiser, Islands will be a good springboard. 

I don't have any strong opinions about adding this to the main repository v/s extras.  In my opinion, everything should be in the main repository. It's a one-time zip download, and users don't even have to compile the modules they don't want. But the extended discussion on this is out of the scope of the PR.

**Comment by cgnitash** [comment]
Looks good. Only pending merge of #221

**Comment by cgnitash** [comment]
Regarding merging of #221, once PR #221 is merged into development, development needs to be merged into this PR.

**Comment by JorySchossau** [comment]
The Lexicase files were already merged in #221 so should be removed here. This is just a note for posterity.

**Pull request merged**
