### PR TITLE
Output Dir to Output Prefix

### PR DESCRIPTION
**Pull request by cgnitash**
From suggestion in #220 
outputDirectory now _behaves_ like outputPrefix.
The prefix can have nested dirs, and the dirs' existence is checked.

Note that the code(and the user setting) must be updated to reflect this semantic change(i.e. outputDirectory to something else). Not done yet, since that's a simple transformation, and I don't want to clutter up the PR. 
outputPrefix seems like a reasonable name.

### CODE REVIEW

**Comment by cgnitash** [comment]
There is a case where this change can affect old users. Hard error with clear error message seems a good way to get people on board, if and when the PR is approved.

**Comment by cliff-bohm** [comment]
Look like this is working correctly.

a) think we should update the parameter name and usage comment in the pull request. If anyone is using this, the change will be evident because the old parameter will no longer exist. I'm good with
GLOBAL-outputPrefix. I think that the usage comment should be changed to reflect that this is where data files will be saved (i.e. as opposed to config files)

b) I would like a better usage message in the case of a missing directory with an additional non-path prefix part.
i.e. if outputPrefix is "./moo/cow_" but moo is missing I would like a more detailed message, like:

Error : found outputPrefix "./moo/cow_" but directory "./moo/" does not exist

**Comment by cgnitash** [comment]
1. Absolutely, this is the PR it must change in. I'll make the changes.

2. Not sure about the error message. Right now it says that the directory doesn't exist. Since _new_ files are being generated, at that point, saying the _prefix_ exists is not really correct.

**Comment by cgnitash** [comment]
Should the default be changed to "./settings_" instead of "./"? This gives a nice example for the default. Also, everything continues to behave as before. 
This does mean that a user specified prefix will override "settings_" as a prefix, but since this was not an available feature before, this won't cause any surprises.

**Comment by cliff-bohm** [comment]
I think your last comment relates to the other pull request. This pull request relates to the prefix for data files, not settings files. The default prefix here should remain './'

as for changing the default for the other pull request. I don't think it would be a good idea to make 'settings_' optional in settings file names. i.e. the default should also be './'

**Comment by cgnitash** [comment]
oops, that's right, wrong PR.

**Comment by cliff-bohm** [comment]
I found an edge case...
if a directory with the same name as the prefix setting already exists an error results:

i.e. if a directory named AAA exists and I run 
```
./mabe -p GLOBAL-outputPrefix AAA
```
the following output is generated
```
Warning: Output files will be saved in Directory "." with the prefix "AAA"
         If you mean to save outputFiles to the Directory "./AAA/", please end outputPrefix with /
Exiting
```
If I delete the AAA directory and rerun all is good.

**Comment by cgnitash** [comment]
Aah yes, that's a bug. I'll change the hard error to a warning, but still save it.

**Comment by cgnitash** [comment]
``================================================================================================= FAILURES ==================================================================================================
/mnt/home/cgnitash/MabeTesting/MABE/mabe_testing/utils/helpers.py:139: AssertionError: test_settings_cfg: 2 changes (see diff-settings.cfg)
/mnt/home/cgnitash/MabeTesting/MABE/mabe_testing/utils/helpers.py:139: AssertionError: test_settings_cfg: 2 changes (see diff-settings.cfg)
=================================================================================== 2 failed, 59 passed in 16.35 seconds ====================================================================================--

**Pull request merged**
