### PR TITLE
Patch command line misread

### PR DESCRIPTION
**Pull request by cgnitash**
Fixes a number of issues. 
Command line arguments to -p no longer have to be escaped. If the argument to a parameter is multi-word, then simply put it in quotes. No escaping of anything required.
e.g. ./mabe -p GLOBAL-initPop " MASTER = any 10 from 'LOD*.csv' " 
(Note: the asterisk passed through command line doesn't expand periods)

If any of -h, -v, or -l is passed on the command line in any combination, and/or with other flags, mabe will print out _all_ the necessary messages and exit. 

Apologies for the large number of changes; I formatted the file. The only function that has been changed is readCommandLine().

### CODE REVIEW

**Comment by VincentRagusa** [comment]
Just for record-keeping's sake the mabe splash screen has been moved to utilities as a part of this PR.

**Comment by cgnitash** [comment]
It's a trivial change, so I don't think it's worth making a separate PR.

**Comment by cliff-bohm** [comment]
general question about parameters with spaces.

in this version:
MABE.exe -p GLOBAL-updates "12" GLOBAL-randomSeed 102
runs to update 12 and randomSeed 102

MABE.exe -p GLOBAL-updates "12 GLOBAL-randomSeed 102"
runs to update 12 and randomSeed 101 (default)

so the question is what happens with characters after spaces. Is it dependent on data type?

**Comment by cliff-bohm** [comment]
Oh, and looks like everything works fine.

**Comment by cgnitash** [comment]
If you put a string that should be translated to a number, then as far as I know, it reads the first bit of the string, and translates that if it can.

This is the same as in settings files though.You can set
updates = 200 and other gunk  #....
and this simply makes GLOBAL-updates 200. 

I'd be happy to add checks for this that apply to Parameters set on the command line or in the settings files. But that's outside the scope of this PR.

**Comment by cliff-bohm** [comment]
That sounds reasonable, I was just curious about the expected behavior.

**Pull request merged**
