### PR TITLE
refactor of mgraph.

### PR DESCRIPTION
**Pull request by VincentRagusa**
loads from file over 20x faster. filters data and plots data faster too. also fixed some minor bugs.

### CODE REVIEW

**Comment by VincentRagusa** [comment]
Also, reduced memory impact of loading files. Forgot to mention.

**Comment by JorySchossau** [comment]
Nice! Does it pass "reasonable" tests for you? It would be nice to list out
roughly what you've already tested.

**Comment by VincentRagusa** [comment]
Yeah, It does all the things I usually do. -conditions, -combineConditions, -data, -repRange.
I won't be able to get back to this for a few days, but I plan to do an exhaustive test of all the parameters.

**Comment by cliff-bohm** [comment]
So far so good. All prints that occur as a result of verbose should be flushed 
print("some info", flush = True)

I'm currently looking at legend creation. this seems to be really expensive when there are many times.
Perhaps there is a better way to do this... if not, it might make sense to chock it up to matplotlib.

**Comment by JorySchossau** [comment]
Changed target branch to 'development'.

**Pull request merged**
