### PR TITLE
Feature csv

### PR DESCRIPTION
**Pull request by cgnitash**
This PR adds memory-mapped CSV support. 
2 new classes are provided:
  CSVReader, which does parsing of csv lines stuff.
  CSV which handles csv files where the first row are unique column headers. 

Many of the functions in Utilities.h can now be removed. Modules that require csv reading and writing, e.g. FiileManager, etc may be able to use the CSV class directly.

In this PR  itself, Loader uses CSV directly as an example. (Note: at the moment some tests fail)

### CODE REVIEW

**Comment by cgnitash** [comment]
**Non-intentional changes** This PR should not be approved till all tests pass.

Test Summary
```
================================================================================================= FAILURES ==================================================================================================
/mnt/home/cgnitash/MabeTesting/MABE/mabe_testing/utils/helpers.py:139: AssertionError: test_saving_after_loading: 2 changes (see diff-snapshot_organisms_0.csv)
/mnt/home/cgnitash/MabeTesting/MABE/mabe_testing/utils/helpers.py:116: AssertionError: test_reload_brains: 2 changes (see diff-diff-testline-reloaded-ConstantValues-data)
=================================================================================== 2 failed, 59 passed in 17.33 seconds ====================================================================================
```
diff-testline-reloaded-ConstantValues-data
```- 0,1,41.000000,41.000000,50.000000,0.000000,35.000000,74.000000,46.000000,68.000000,98.000000,26.000000,5000,9.000000,9.000000,"[9.000000]",-1,"[-1]"
?     -
+ 0,1,1.000000,41.000000,50.000000,0.000000,35.000000,74.000000,46.000000,68.000000,98.000000,26.000000,5000,9.000000,9.000000,"[9.000000]",-1,"[-1]"
```

**Comment by JorySchossau** [comment]
Meeting with Nitash we tested this a lot more, and discovered something about his HPCC user environment configuration was causing this issue, though how is completely a mystery. I've run complete tests on a variety of systems and configurations all passing without issue. (see next comment)

**Comment by JorySchossau** [comment]
Test results
=== 61 passed in 14.47 seconds ===

**Comment by JorySchossau** [comment]
@cliff-bohm, if there are any CSV reading/writing specific tests that should be added, now is the time to help think of them and list here.

**Comment by cgnitash** [comment]
Clean up of Utilites.h. redundant/unused functions removed. 
CSV related stuff can now use CSV.h 
A bunch of utilities are only used by BerryWorld and are moved there. That leaf can be cleaned up whenever.

All tests passing.

**Comment by cgnitash** [comment]
Refreshed PR passing tests label, since the label is only valid _after_ the latest commit.

**Comment by cliff-bohm** [comment]
I found a few problematic edge cases:

1) '+' does not work as a separator

2) given this code:

```
	std::string testStr2 = "[1- 3-|5 -7|]";
	CSVReader readerPLS('-','|');
	testList =
		readerPLS.parseLine(testStr2.substr(1, testStr2.size() - 2));

	for (auto &e : testList) {
		std::cout << e << " * ";
	}
	std::cout << std::endl;
```
you get:   1 * 3 * |5 *
but should get:   1 * 3 * |5 -7| *

Features I would like/suggestions:
While it's not part of the CSV standard, I would like the CSV tools to include some extra functionality.

a) () and [] should be treated like characters - included checking for matching.
i.e., everything within the outer set is a single object
This feature should be optional on construction.

e.g.,
a,(b+d[1],2),c -> "a","(b+d[1],2)","c"

b) I miss the convert to csv(string, container) function - I could be persuaded that it's not needed.
Or, is it there, and I just missed it?

c) I would like the converter to strip of leading [ and trailing ] automatically. This in combination with a) allows a string like [a,[b,c],[d,[e,f,g]]] to be easily deconstructed without making the user pull off leading [ and trailing ]. Same for (). as with a) this should probably be optional.

e.g.,
(b+d[1],2) -> "b+d[1]","2"

**Comment by cgnitash** [comment]
Edge cases fixed.
a) CSVReader now takes also takes pairs of quotation characters. e.g.
` r(',','[',']');`
This might take care of these requirements. The default close quotation is just the open quotation.
b)CSVreader.parseLine() does this.
c) This doesn't seem to really be a CSV thing. Also, it's a fairly trivial operation to be done at the call site. We might also consider looking at where these strings are generated in the first place.

**Comment by cgnitash** [comment]
As my previous comment says, my responses are for the simple version of rules.

Note that I'm not saying we don't need these features, I'm just saying it falls out of the purview of CSV functionality. We will definitely add the needed functionality, in the correct fashion.

I still don't see the issue with the whitespace. Have you tried it with the latest version of this branch? If the problem persists we'll solve it in lab.

**Comment by cliff-bohm** [comment]
maybe I'm doing something wrong. I just retested this and get the same result.

here is my history:```
  539  git fetch public
  540  git checkout -b development --track public/development
  541  git checkout feature-CSV
  542  vim main.cpp                                                          #hack example code into main
  543  python pythonTools/mbuild.py -p 7
  544  vim main.cpp                                                           #forgot include for csv
  545  python pythonTools/mbuild.py -p 7
  546  ./mabe.exe
  547  history
```
the output from 546 is;
```
cliff@DESKTOP-PNJPG1F MINGW64 ~/Desktop/MabePullCheck
$ ./mabe.exe
1 * 3 * |5 *



        MM   MM      A       BBBBBB    EEEEEE
        MMM MMM     AAA      BB   BB   EE
```

**Comment by cgnitash** [comment]
Currently, CSV only parses delimiter seperated strings with one type of quotation character.

parseCSVline will give trouble with whitespace. This can be fixed only by having a separate function to convert to strings, and one to convert to al other types.

**Comment by cliff-bohm** [comment]
Sorry for the confusion. I did not mean having different quotation mark characters - I think we have agreed that that should not be supported. I was talking about a string like this:
a,b"c,d","e,f"
assuming ',' and '"' are the separator and quote chars, what behavior are you proposing for this string?

**Comment by cgnitash** [comment]
This would become the list of strings
a
b
c,d
e,f

**Comment by cliff-bohm** [comment]
Okay, that looks like what I would expect. what about this one?

a,"b"c,d,  e,  "f g ",h"i"

**Comment by JorySchossau** [comment]
1) We need a volunteer to figure out how to patch this PR to get whitespaces to work before we can merge it.
2) Consistency testing (informal or formal) needs to be done with the complex use cases presented in I think BerryWorld and maybe others.
3) In the future, we should separate out whitespace code cleanup into a separate PR to make code review of such a large PR much easier.

**Pull request closed without merging**
