### PR TITLE
added Random function randomIota

### PR DESCRIPTION
**Pull request by cgnitash**
Added Random function randomIota(m,n)
Returns a vector of m numbers, randomly drawn from the range (0,n-1)

### CODE REVIEW

**Comment by cgnitash** [comment]
Obviously this PR changes nothing.

**Comment by cliff-bohm** [comment]
The order of the values is random aswell, correct? If so, that should be reflected in the comment (and eventual usage). Also is it ineffecent to use this with m = n when you want a random ordering of 0 to n-1?

**Comment by cgnitash** [comment]
@cliff-bohm  had suggested a number of variants on this functionality. Comment here, they can be added in the same PR.

**Comment by cliff-bohm** [comment]
Suggested functions:

sample(min,max,step,size);
// return a vector randomly filled with size values between min and max
// values may repeat

_sample_(max,size) - 
return size values in range 0 to (max-1) 
_sample_(max,min,size) - 
return size values in range min to (max-1)
_sample_(max,min,step,size) - 
return size values in range min to (max-1) on step

_sample_unique_(min,max,step,size);
// return a vector randomly filled with size values between min and max
// values may **not** repeat
_sample_unique_(max) -
return max values in range 0 to (max-1) with out replacement
_sample_unique_(max,min) -
return (min - (max-1)) values in range min to (max-1) with out replacement
_sample_unique_(max,min,step) -
return (min - (max-1)) values in range min to (max-1) on step with out replacement
_sample_unique_(max,min,step,size) -
return size values in range min to (max-1) on step with out replacement ( size must be <= (min - (max-1)) ).

**Comment by cgnitash** [comment]
This PR is superseded by #253. The suggestions for new functions are moved there as well.

**Pull request closed without merging**
